### ISSUE TITLE
String comparitions do not work except = and !=.

### ISSUE THREAD

**Issue by lamduongngoc** [pgspider/influxdb_fdw#13]
According to https://github.com/influxdata/influxdb/issues/8265, InfluxDB cannot execute string comparison other than “=” and “!=” in WHERE clause.
Currently, InfluxDB FDW push down string comparison to InfluxDB, so it gets wrong result.
For example, the following query is executed on Postgres 9.6.17.

Actual result
```
select count(*) from ft2 where y >= 'x';
 count
-------

```
Expected result
```
select count(*) from ft2 where y >= 'x';
 count
-------
      10

```
This test is OK on Postgres 12.
InfluxDB FDW should execute string comparison on local

**Comment by hrkuma** [comment]
We have fixed in Release v0.3.0.
So we'd like to close this issue.
