### ISSUE TITLE
GROUP BY only works with time and tag dimensions

### ISSUE THREAD

**Issue by lamduongngoc** [pgspider/influxdb_fdw#16]
The following query is failed on  Postgres 10.12, 11.7, 12
```
select count(c2) w, c2 x, 5 y, 7.0 z from ft1 group by 2, y, 9.0::int order by 2;
ERROR:  influxdb_fdw : only time and tag dimensions allowed
```
InfluxDB allows only time and tag fields in GROUP BY. InfluxDB FDW should not push down fields other than time and tag fields.

**Comment by hrkuma** [comment]
We have fixed in Release v0.3.0.
So we'd like to close this issue.
