### ISSUE TITLE
GROUP BY does not support FIELD KEY having arithmetic

### ISSUE THREAD

**Issue by lamduongngoc** [pgspider/influxdb_fdw#17]
The following query is failed on Postgres 10.12, 11.7, 12
```
select c2/2, sum(c2) * (c2/2) from ft1 group by c2/2 order by c2/2;
ERROR:  influxdb_fdw : error parsing query: found FROM, expected identifier, string, number, bool at line 1, char 9
```

InfluxDB does not support the arithmetic field (c2/2) in GROUP BY. InfluxDB FDW should execute on local.

**Comment by hrkuma** [comment]
We have fixed in Release v0.3.0.
So we'd like to close this issue.
