### ISSUE TITLE
the foreign table with wrong field would crash the database

### ISSUE THREAD

**Issue by cobolbaby** [pgspider/influxdb_fdw#39]
When I create the external table, I reference an influxdb field that doesn't exist. Then as soon as I query the external table, the PostgreSQL server crashes.

For example, the fields in InfluxDB include A/B/C, but I defined an extra D when defining in PostgreSQL.

```
2023-11-13 16:06:50.231 CST,,,45,,64a22757.2d,915,,2023-07-03 09:41:43 CST,,0,LOG,00000,"server process (PID 3554481) was terminated by signal 11: Segmentation fault","Failed process was running:     select * from dm.iot_sqt_agv_status1 limit 10  ",,,,,,,,""
2023-11-13 16:06:50.231 CST,,,45,,64a22757.2d,916,,2023-07-03 09:41:43 CST,,0,LOG,00000,"terminating any other active server processes",,,,,,,,,""
```

**Comment by mkgrgis** [comment]
Hello @cobolbaby ! Please share your `CREATE FOREIGN TABLE` and `CREATE SERVER` (please without your network requisites). Please note there is 3 different client mode for `influxdb_fdw` and different data read modes for foreign tables.

**Comment by cobolbaby** [comment]
```sql
CREATE SERVER influxdb_iot
    FOREIGN DATA WRAPPER influxdb_fdw
    OPTIONS (dbname 'iot-env', host 'http://infra-influx.ipt.inventec.net', port '80', version '1', retention_policy '');

drop FOREIGN TABLE dm.iot_sqt_agv_status111;
CREATE FOREIGN TABLE dm.iot_sqt_agv_status111(
    "time" timestamp with time zone NULL,
    "Status" character varying NULL COLLATE pg_catalog."default",
    "agvCode" character varying NULL COLLATE pg_catalog."default",
    "agvState" character varying NULL COLLATE pg_catalog."default",
    "exceptionCode" character varying NULL COLLATE pg_catalog."default",
    pointcode character varying NULL COLLATE pg_catalog."default",
    power double precision NULL,
    zoncode character varying NULL COLLATE pg_catalog."default",
    unkonw_filed character varying NULL COLLATE pg_catalog."default"
)
SERVER influxdb_iot
OPTIONS (table 'F3AGV.status1', tags 'Status,agvCode,agvState,exceptionCode,pointcode,power,zonCode', schemaless 'true');
```

**Comment by mkgrgis** [comment]
Thanks, @cobolbaby ! You have InfluxDB ver 1.x in [schemaless mode](https://github.com/pgspider/influxdb_fdw#schemaless-feature). Look like this tags usage is normal https://github.com/pgspider/influxdb_fdw/blob/c7cc9f2138b87b6761476fed11381104022bb0de/expected/15.0/schemaless/influxdb_fdw.out#L128 How do you think, is this representative test case near your problem or this can be identifier problem? Is your InfluxDB Unicode database in UTF-8?
Could you test with sample data "tag1", "Tag1", "tAG1" etc.? Please note https://github.com/pgspider/influxdb_fdw#identifier-case-handling

**Comment by mkgrgis** [comment]
@cobolbaby , could you share unsuccessfully `SELECT` result after such SQL as  `set client_min_messages='debug4';` ?

**Comment by mkgrgis** [comment]
Look like `unkonw_filed` was your problem. So, non-existed filds diagnostics in `tags` is real problem of this FDW. Isn't it?

**Comment by cobolbaby** [comment]
>  is this representative test case near your problem or this can be identifier problem

What I refer to is https://github.com/pgspider/influxdb_fdw#create-foreign-table. I didn't use the jsonb type, I guess jsonb should be fine.

>  share unsuccessfully SELECT result after such SQL as set client_min_messages='debug4';

- Segmentation fault caused by the unkonw_filed (not existed)

```bash
bdc_test=# set client_min_messages='debug4';
SET
bdc_test=# select * from dm.iot_sqt_agv_status1 limit 10;
DEBUG:  influxdb_fdw : influxdb_fdw_handler
DEBUG:  influxdb_fdw : influxdbGetForeignRelSize
DEBUG:  influxdb_fdw : influxdbGetForeignPaths
DEBUG:  influxdb_fdw : influxdbGetForeignUpperPaths
DEBUG:  influxdb_fdw : influxdbGetForeignPlan
DEBUG:  influxdb_fdw : influxdbBeginForeignScan
DEBUG:  influxdb_fdw : influxdbIterateForeignScan
DEBUG:  influxdb_fdw: new InfluxDB connection 0x5d52c78fd050 for server "influxdb_iot" (user mapping oid 57344, userid 10)
DEBUG:  influxdb_fdw : query: SELECT * FROM "F3AGV.status1" LIMIT 10
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 
```

- The unkonw_filed field (not existed) is filled with the value of zonCode

```
bdc_test=# set client_min_messages='debug4';
SET
bdc_test=# select * from dm.iot_sqt_agv_status2 limit 10;
DEBUG:  influxdb_fdw : influxdbGetForeignRelSize
DEBUG:  influxdb_fdw : influxdbGetForeignPaths
DEBUG:  influxdb_fdw : influxdbGetForeignUpperPaths
DEBUG:  influxdb_fdw : influxdbGetForeignPlan
DEBUG:  influxdb_fdw : influxdbBeginForeignScan
DEBUG:  influxdb_fdw : influxdbIterateForeignScan
DEBUG:  influxdb_fdw : query: SELECT * FROM "F3AGV.status1" LIMIT 10
DEBUG:  influxdb_fdw : influxdbIterateForeignScan
DEBUG:  influxdb_fdw : influxdbIterateForeignScan
DEBUG:  influxdb_fdw : influxdbIterateForeignScan
DEBUG:  influxdb_fdw : influxdbIterateForeignScan
DEBUG:  influxdb_fdw : influxdbIterateForeignScan
DEBUG:  influxdb_fdw : influxdbIterateForeignScan
DEBUG:  influxdb_fdw : influxdbIterateForeignScan
DEBUG:  influxdb_fdw : influxdbIterateForeignScan
DEBUG:  influxdb_fdw : influxdbIterateForeignScan
DEBUG:  influxdb_fdw : influxdbIterateForeignScan
DEBUG:  influxdb_fdw : influxdbEndForeignScan
            time            | Status | agvCode | agvState | exceptionCode | pointcode | power | unkonw_filed 
----------------------------+--------+---------+----------+---------------+-----------+-------+--------------
 2023-10-31 08:00:57.077+08 | 2      | 011     | BUSY     |               | KhkfeG    |  0.59 | 3CBF
 2023-10-31 08:00:57.077+08 | 0      | 016     | IDLE     |               | byjXTk    |  0.65 | 3C1F
 2023-10-31 08:00:57.077+08 | 0      | 058     | IDLE     |               | sB3H8t    |   0.7 | 3C2F
 2023-10-31 08:00:57.077+08 | 0      | 059     | IDLE     |               | tDEXnZ    |   0.7 | 3C1F
 2023-10-31 08:00:57.077+08 | 2      | 017     | BUSY     |               | R45bRB    |  0.85 | 3CBF
 2023-10-31 08:00:57.077+08 | 2      | 014     | BUSY     |               | 5NmmSz    |  0.76 | 3C2F
 2023-10-31 08:00:57.077+08 | 2      | 018     | BUSY     |               | Q3BpSJ    |  0.44 | 3CBF
 2023-10-31 08:00:57.077+08 | 0      | 040     | IDLE     |               | KmeBTj    |  0.74 | 3C2F
 2023-10-31 08:00:57.077+08 | 0      | 012     | IDLE     |               | WHJmCB    |  0.73 | 3C2F
 2023-10-31 08:00:57.077+08 | 2      | 019     | BUSY     |               | mzm2is    |  0.54 | 3C2F
(10 rows)
```

> Look like unkonw_filed was your problem. So, non-existed fields diagnostics in tags is real problem of this FDW. Isn't it?

To be precise, the bug will arise if more fields are defined in PG. In addition, theoretically the unkonw_field in the  dm.iot_sqt_agv_status2 should be empty, but I don’t know why it is filled with the value of a specific field at the end.

**Comment by cobolbaby** [comment]
> Could you test with sample data "tag1", "Tag1", "tAG1" etc.? 

If the field in Influxdb is `Tag1`, it must be defined as `Tag1` in PG, otherwise the query result would return empty.

**Comment by mkgrgis** [comment]
> To be precise, the bug will arise if more fields are defined in PG. In addition, theoretically the `unkonw_field` in the `dm.iot_sqt_agv_status2` should be empty, but I don’t know why it is filled with the value of zoneCode field at the end.

This look like complete problem localisation. Please refer a function under https://github.com/pgspider/influxdb_fdw/blob/c7cc9f2138b87b6761476fed11381104022bb0de/influxdb_query.c#L68 in context of https://github.com/pgspider/influxdb_fdw/blob/c7cc9f2138b87b6761476fed11381104022bb0de/influxdb_fdw.c#L1475

Do you think this is wrong `attnum` value after end of normal cycle?

> If the field in Influxdb is `Tag1`, it must be defined as `Tag1` in PG, otherwise the query result would return empty.

No, I am about something other.  Could you make some independent tests like in https://github.com/pgspider/sqlite_fdw#identifier-case-handling because this is yet not described for InfluxDB? Can exists both `Tag1` and `tAg1` in InfluxDB ? This is not your problem but should allow better detect non-existed fields.

**Comment by cobolbaby** [comment]
> Do you think this is wrong attnum value after end of normal cycle?

No, I think the root cause is in this code block:

https://github.com/pgspider/influxdb_fdw/blob/c7cc9f2138b87b6761476fed11381104022bb0de/influxdb_fdw.c#L1146-L1150

**Comment by lamdn1409** [comment]
@cobolbaby @mkgrgis 

From your post [here ](https://github.com/pgspider/influxdb_fdw/issues/39#issuecomment-1839947421), I see that this form of the foreign table should be used in non-schemaless mode (by default 'schemaless' option is false). If you want to use the foreign table in schemaless mode, please change it to the following format.

```
The columns are fixed with names and types as below:
  (time timestamp with time zone, tags jsonb, fields jsonb)
```
Please check more details in the description of [README.md](https://github.com/pgspider/influxdb_fdw/blob/master/README.md) file.

However, I think InfluxDB FDW should be improved to handle the case that incorrect configuration of the foreign table is detected.
At the moment, please use the foreign table in the correct way to avoid unexpected behavior first.

**Comment by cobolbaby** [comment]
I understand, I just hope that influxdb_fdw can improve its exception handling logic to prevent PG from restarting unexpectedly.

**Comment by lamdn1409** [comment]
@cobolbaby 
I'd like to inform this issue was fixed by PR #53.

**Comment by mkgrgis** [comment]
@cobolbaby , please verify. In my environment there are no problems.

**Comment by cobolbaby** [comment]
Verified, the definition error will result in the following error message:

```
ERROR:  influxdb fdw: invalid column in schemaless mode. Only time, time_text, tags and fields columns are accepted. 

SQL state: XX000
```
