### ISSUE TITLE
influxdb database as schema in influx_fdw

### ISSUE THREAD

**Issue by Sugaroverdose** [pgspider/influxdb_fdw#4]
Currently, if you have multiple databases on influxdb side, you need to create multiple servers and user mappings for each database.
Wouldn't it be better to migrate 'dbname' option from 'create server' into 'schema'(which is always 'public' if i get it right) in 'import foreign schema' or 'create foreign table', so you could actually use them to import all desired tables without creating huge amount of servers and user mappings?

**Comment by mochizk** [comment]
Thanks for your proposal.

I think there are advantages in your proposal as you said, but we have applications depending on current behavior and it takes some work to change it. So I will not change current behavior.
I hope you understand that.

**Comment by Sugaroverdose** [comment]
Hello @mochizk 

It's just UX concerns which would actually make this fdw a lot better.
I've actually expected that you may already rely on current implementation, so i would suggest to leave this issue for better times :)

**Comment by mochizk** [comment]
OK, I will reconsider the current implementation if there is any chance.
For now, I'd like to close this ticket.
