### ISSUE TITLE
 Segmentation fault caused by SQL subquery

### ISSUE THREAD

**Issue by cobolbaby** [pgspider/influxdb_fdw#40]
```sql
select version();

-- PostgreSQL 12.17 (Debian 12.17-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit

select * from pg_available_extensions where name = 'influxdb_fdw';

-- "influxdb_fdw"	"1.3"	"1.3"	"InfluxDB Foreign Data Wrapper"

-- DROP SERVER influxdb_iot

CREATE SERVER influxdb_iot
    FOREIGN DATA WRAPPER influxdb_fdw
    OPTIONS (dbname 'iot-env', host 'http://infra-influx.ipt.inventec.net', port '80', version '1', retention_policy '');

-- DROP USER MAPPING FOR bdcuser SERVER influxdb_iot

CREATE USER MAPPING FOR bdcuser SERVER influxdb_iot
    OPTIONS ("user" 'iot', password '******');

-- DROP FOREIGN TABLE dm.iot_sqt_agv_count;

CREATE FOREIGN TABLE dm.iot_sqt_agv_count(
    "time" timestamp with time zone NULL,
    "agvState" character varying NULL COLLATE pg_catalog."default",
    value numeric NULL
)
    SERVER influxdb_iot
    OPTIONS (table 'F3AGV.count', tags 'agvState,value', schemaless 'false');

SELECT max(time) from dm.iot_sqt_agv_count where time > now() - interval '1 d';

-- "2023-12-04 19:15:53.318+08"

select * from dm.iot_sqt_agv_count 
where time = '2023-12-04 19:15:53.318+08'

"2023-12-04 19:15:53.318+08"	"BUSY"	57
"2023-12-04 19:15:53.318+08"	"CHARGING"	7
"2023-12-04 19:15:53.318+08"	"ERROR"	1
"2023-12-04 19:15:53.318+08"	"IDLE"	16
"2023-12-04 19:15:53.318+08"	"LOCKED"	7
"2023-12-04 19:15:53.318+08"	"offlineAGV"	4
"2023-12-04 19:15:53.318+08"	"onlineAGV"	88
"2023-12-04 19:15:53.318+08"	"totalAGV"	92

explain 
select * from dm.iot_sqt_agv_count 
where time = --'2023-12-04 19:15:53.318+08'
(SELECT max(time) from dm.iot_sqt_agv_count where time > now()-interval '1d');

"Foreign Scan on iot_sqt_agv_count  (cost=865.14..859.14 rows=4 width=72)"
"  InitPlan 1 (returns $0)"
"    ->  Aggregate  (cost=855.13..855.14 rows=1 width=8)"
"          ->  Foreign Scan on iot_sqt_agv_count iot_sqt_agv_count_1  (cost=10.00..853.00 rows=853 width=8)"


select * from dm.iot_sqt_agv_count 
where time = --'2023-12-04 19:15:53.318+08'
(SELECT max(time) from dm.iot_sqt_agv_count where time > now()-interval '1d');

ERROR: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
```

I don't know why I got the error 'Segmentation fault':

```log
2023-12-04 19:18:25.379 CST [11] LOG:  server process (PID 330885) was terminated by signal 11: Segmentation fault
2023-12-04 19:18:25.379 CST [11] DETAIL:  Failed process was running: 
	select * from dm.iot_sqt_agv_count 
	where time = --'2023-12-04 19:15:53.318+08'
	(SELECT max(time) from dm.iot_sqt_agv_count where time > now()-interval '1d');
2023-12-04 19:18:25.379 CST [11] LOG:  terminating any other active server processes
```

**Comment by cobolbaby** [comment]
@mkgrgis Maybe you could identify the bug together, Thanks a lot.

**Comment by mkgrgis** [comment]
Hello, @cobolbaby ! I have never works with InfluxDB and I am not PGSpider team member, but my `sqlite_fdw` experience allow to locate your problem in https://github.com/pgspider/influxdb_fdw/blob/master/deparse.c This look like there is no needed deparse `WHERE` rules for your case. Pushdowning of your query to InfluxDB should use [syntax transformation](https://github.com/pgspider/influxdb_fdw#group-by-time-intervals-and-fill) but I am not sure if there is pushdowning or if there is correct result of subquery. The main problem also for pure PostgreSQL is the same table in query and subquery. This cause very specific query plans and I am not sure this plans in well-implemented in this FDW.

**Comment by mkgrgis** [comment]
@cobolbaby , could you try the same query with [window functions](http://www.postgres.cn/docs/14/tutorial-window.html) or with `HAVING`? Also please `explain `**`verbose`** for 
```sql
select * from dm.iot_sqt_agv_count 
where time = --'2023-12-04 19:15:53.318+08'
(SELECT max(time) from dm.iot_sqt_agv_count where time > now()-interval '1d');
```
This can be more helpful sometimes.

**Comment by cobolbaby** [comment]
```
explain verbose
select * from dm.iot_sqt_agv_count 
where time = --'2023-12-04 19:15:53.318+08'
(SELECT max(time) from dm.iot_sqt_agv_count where time > now()-interval '1d');

"Foreign Scan on dm.iot_sqt_agv_count  (cost=865.14..859.14 rows=4 width=72)"
"  Output: iot_sqt_agv_count.""time"", iot_sqt_agv_count.""agvState"", iot_sqt_agv_count.value"
"  InfluxDB query: SELECT * FROM ""F3AGV.count"" WHERE ((time = $1))"
"  InitPlan 1 (returns $0)"
"    ->  Aggregate  (cost=855.13..855.14 rows=1 width=8)"
"          Output: max(iot_sqt_agv_count_1.""time"")"
"          ->  Foreign Scan on dm.iot_sqt_agv_count iot_sqt_agv_count_1  (cost=10.00..853.00 rows=853 width=8)"
"                Output: iot_sqt_agv_count_1.""time"", iot_sqt_agv_count_1.""agvState"", iot_sqt_agv_count_1.value"
"                InfluxDB query: SELECT * FROM ""F3AGV.count"" WHERE ((time > (now() - 1d0h0m0s0u)))"
```

**Comment by cobolbaby** [comment]
> could you try the same query with [window functions](http://www.postgres.cn/docs/14/tutorial-window.html) or with HAVING

Can you give me an example so I can execute it?

**Comment by cobolbaby** [comment]
>  I have never works with InfluxDB and I am not PGSpider team member

Many thanks for your reply. Could you inform me about the current maintainer(s) of the project?

**Comment by cobolbaby** [comment]
> For me there is double quoting and unusual interval. Have I mistaken here?

No problem here. The presence of double quotation marks is because I copied the output results from the web interface of pgAdmin.

**Comment by cobolbaby** [comment]
> Perhaps influxdb_fdw does not yet support InitPlan type operators.

@mkgrgis Regarding this issue, can you locate the problematic code block?

**Comment by mkgrgis** [comment]
> Regarding this issue, can you locate the problematic code block?

@cobolbaby , `InitPlan` look like some execution function in PostgreSQL see https://doxygen.postgresql.org/execMain_8c.html#ae7f37b09dfd050780c4751568a93184f Unfortunately I have no normal experience with plan nodes. Also I can tell you there is no special `InitPlan` code infrastructure in this FDW, in `sqlite_fdw`, in `[firebird_fdw](https://github.com/ibarwick/firebird_fdw)` or in `[oracle_fdw](https://github.com/laurenz/oracle_fdw/)`. Look like `InitPlan` is not one of FDW code infrastructure subjects. Hence I can not understand what exact means "support InitPlan type operators". I think this is implemented in PostgreSQL main code for all FDW and not only for FDWs.

**Comment by cobolbaby** [comment]
If the problem isn't with InitPlan, I'm really puzzled about where the issue might be. It's not easy for me to debug step-by-step.

**Comment by mkgrgis** [comment]
@cobolbaby , what about `psql` listing with `set client_min_messages='debug4';` and the crash? Most of main FDW function have `DEBUG3` initial message.

**Comment by cobolbaby** [comment]
```
...
DEBUG:  influxdb_fdw : influxdbIterateForeignScan
...
DEBUG:  influxdb_fdw : influxdbIterateForeignScan
DEBUG:  influxdb_fdw : influxdbIterateForeignScan
DEBUG:  influxdb_fdw : influxdbIterateForeignScan
server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
The connection to the server was lost. Attempting reset: Failed.
!> 
```

**Comment by mkgrgis** [comment]
So. the problem is near `influxdbIterateForeignScan` https://github.com/pgspider/influxdb_fdw/blob/c7cc9f2138b87b6761476fed11381104022bb0de/influxdb_fdw.c#L1593-L1594 during second query `SELECT * FROM "F3AGV.count" WHERE ((time = $1))`. Also can be affected `influxdbBeginForeignScan` or `influxdbEndForeignScan` if there is problem of unclear buffer.

**Comment by cobolbaby** [comment]
Who can help resolve this critical bug? @all

**Comment by mkgrgis** [comment]
@cobolbaby , look like this repository [is not very active](https://github.com/pgspider/influxdb_fdw/graphs/contributors). Maybe someone from pgspider team will read our diagnostics.

**Comment by weiting1lee** [comment]
@cobolbaby and @mkgrgis ,

I apologize for the inconvenience caused by this issue. I'm investigating the segmentation fault, which seems related to InitPlan type operators. I will thoroughly analyze influxdbIterateForeignScan and other related functions.

Thanks for your detailed information and suggestions. I'll keep you updated on our progress.

Thank you for your patience and support!

**Comment by mkgrgis** [comment]
@weiting1lee , could someone from pgspider team also investigate not compilable for new PostreSQL version [dynamodb_fdw/](https://github.com/pgspider/dynamodb_fdw/issues/7) ?

**Comment by weiting1lee** [comment]
@mkgrgis 
I will notify the team internally to follow it.

**Comment by cobolbaby** [comment]
@weiting1lee Any progress ?

**Comment by weiting1lee** [comment]
@cobolbaby 
We are currently investigating the segmentation fault issue you reported. Based on our findings, the problem arises due to the parameter not being initialized during the scanning query execution.
We are discussing solutions. We will update here as we make progress.

**Comment by cobolbaby** [comment]
@weiting1lee "Three months have passed, is there any progress?

**Comment by weiting1lee** [comment]
@cobolbaby 
Thank you for your patience. While resolving issues related to InitPlan type operators, we identified some additional problems with time operations. Please bear with us a little longer. I really appreciate your follow-up.

**Comment by lamdn1409** [comment]
@cobolbaby
I'd like to inform this issue was fixed by the PR https://github.com/pgspider/influxdb_fdw/pull/54

**Comment by cobolbaby** [comment]
Verified.
