### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by qhq16** [pgspider/influxdb_fdw#7]
When i make it with: make USE_PGXS=1 with_llvm=no,
this error happend.
/usr/bin/ld: query.a(go.o): relocation R_X86_64_TPOFF32 against `runtime.tlsg' can not be used when making a shared object; recompile with -fPIC
query.a: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
/usr/lib/postgresql/10/lib/pgxs/src/makefiles/../../src/Makefile.shlib:308: recipe for target 'influxdb_fdw.so' failed
make: *** [influxdb_fdw.so] Error 1

**Comment by mochizk** [comment]
Thanks for reporting the issue!
I think the latest commit fixes the issue,  so could you try the latest code?

I cannot reproduce the issue, so If it'not fixed, 
please let me know Go and PostgreSQL version on your environment.

**Comment by qhq16** [comment]
This problem still exist. These are my go and postgresql version. I set my GOPATH=/usr/lib/go-1.6/. Then i execute ：go get github.com/influxdata/influxdb1-client/v2  as root. Then i add pg_config to PATH, and execute : make USE_PGXS=1 with_llvm=no, then the same problem occur again.
Please help me!

root@i-hmrtocq8:~# go version
go version go1.6.2 linux/amd64

ubuntu@i-hmrtocq8:~$ sudo -u postgres psql
psql (10.9 (Ubuntu 10.9-1.pgdg16.04+1))
Type "help" for help.
postgres=#

**Comment by mochizk** [comment]
Thanks. 
I confirm it can be compiled in Go 1.10. Could you use Go 1.10 or newer?

**Comment by qhq16** [comment]
Oh, thank you very much! I tried go with version 1.10.4, and this problem has been solved.
